export const sendSlackAlert = async (
  webhookUrl: string, 
  message: string, 
  type: 'success' | 'error', 
  metadata?: Record<string, string>
) => {
  if (!webhookUrl) return;

  const color = type === 'success' ? '#0aff0a' : '#ff0a0a'; // neon-green or neon-red
  const title = type === 'success' ? '🚀 Agent Mission Complete' : '🚨 Agent Mission Critical Error';
  
  // Construct Slack Blocks for a rich UI
  const blocks: any[] = [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: title,
        emoji: true
      }
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Status Update:*\n${message}`
      }
    },
    {
      type: "divider"
    }
  ];

  if (metadata) {
    const fields = Object.entries(metadata).map(([k, v]) => ({
      type: "mrkdwn",
      text: `*${k.charAt(0).toUpperCase() + k.slice(1)}:*\n${v}`
    }));
    
    // Slack sections allow up to 10 fields
    if (fields.length > 0) {
      blocks.push({
        type: "section",
        fields: fields.slice(0, 10)
      });
    }
  }

  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: `Generated by GHL Agent Command Center • ${new Date().toLocaleTimeString()}`
      }
    ]
  });

  try {
    // Using no-cors because Slack Webhooks do not send CORS headers for browser fetch.
    // The request will succeed (opaque response), but we won't see the status code.
    await fetch(webhookUrl, {
      method: 'POST',
      mode: 'no-cors', 
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        attachments: [
          { 
            color: color, 
            blocks: blocks 
          }
        ] 
      }) 
    });
    return true;
  } catch (e) {
    console.error("Slack integration error:", e);
    return false;
  }
};