/**
 * Agent Type Definitions and Capabilities
 * Comprehensive agent registry with 64 specialized agent types
 */

import type { AgentType, AgentCapabilities } from './types';

export interface AgentTypeDefinition {
  type: AgentType;
  name: string;
  description: string;
  capabilities: AgentCapabilities;
  defaultConfig: {
    autonomyLevel: number;
    learningEnabled: boolean;
    maxTasksPerHour: number;
  };
  category: 'development' | 'architecture' | 'testing' | 'devops' | 'data' | 'business' | 'specialized';
}

/**
 * Comprehensive agent type registry
 */
export const AGENT_TYPES: Record<AgentType, AgentTypeDefinition> = {
  // Core Development Agents
  coordinator: {
    type: 'coordinator',
    name: 'Swarm Coordinator',
    description: 'Orchestrates and manages other agents, handles task distribution',
    capabilities: {
      codeGeneration: false,
      codeReview: true,
      testing: false,
      documentation: true,
      research: false,
      analysis: true,
      webSearch: false,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: false,
      languages: [],
      frameworks: [],
      domains: ['coordination', 'planning', 'monitoring'],
      tools: ['task-scheduler', 'agent-manager', 'monitoring'],
      maxConcurrentTasks: 10,
      maxMemoryUsage: 512 * 1024 * 1024,
      maxExecutionTime: 3600000,
      reliability: 0.95,
      speed: 0.9,
      quality: 0.9,
    },
    defaultConfig: {
      autonomyLevel: 0.9,
      learningEnabled: true,
      maxTasksPerHour: 100,
    },
    category: 'specialized',
  },

  researcher: {
    type: 'researcher',
    name: 'Research Agent',
    description: 'Performs research and data gathering',
    capabilities: {
      codeGeneration: false,
      codeReview: false,
      testing: false,
      documentation: true,
      research: true,
      analysis: true,
      webSearch: true,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: false,
      languages: [],
      frameworks: [],
      domains: ['research', 'analysis', 'information-gathering'],
      tools: ['web-search', 'document-analysis', 'data-extraction'],
      maxConcurrentTasks: 5,
      maxMemoryUsage: 256 * 1024 * 1024,
      maxExecutionTime: 600000,
      reliability: 0.9,
      speed: 0.8,
      quality: 0.9,
    },
    defaultConfig: {
      autonomyLevel: 0.8,
      learningEnabled: true,
      maxTasksPerHour: 20,
    },
    category: 'business',
  },

  coder: {
    type: 'coder',
    name: 'Developer Agent',
    description: 'Writes and maintains code',
    capabilities: {
      codeGeneration: true,
      codeReview: true,
      testing: true,
      documentation: true,
      research: false,
      analysis: true,
      webSearch: false,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: true,
      languages: ['typescript', 'javascript', 'python', 'rust', 'go'],
      frameworks: ['react', 'node', 'express', 'fastapi', 'django'],
      domains: ['web-development', 'backend', 'api-design'],
      tools: ['git', 'editor', 'debugger', 'linter', 'formatter'],
      maxConcurrentTasks: 3,
      maxMemoryUsage: 512 * 1024 * 1024,
      maxExecutionTime: 1200000,
      reliability: 0.95,
      speed: 0.7,
      quality: 0.95,
    },
    defaultConfig: {
      autonomyLevel: 0.6,
      learningEnabled: true,
      maxTasksPerHour: 10,
    },
    category: 'development',
  },

  analyst: {
    type: 'analyst',
    name: 'Data Analyst',
    description: 'Analyzes data and generates insights',
    capabilities: {
      codeGeneration: false,
      codeReview: true,
      testing: false,
      documentation: true,
      research: false,
      analysis: true,
      webSearch: false,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: false,
      languages: ['python', 'r', 'sql'],
      frameworks: ['pandas', 'numpy', 'matplotlib'],
      domains: ['data-analysis', 'statistics', 'visualization'],
      tools: ['data-processor', 'chart-generator', 'statistical-analyzer'],
      maxConcurrentTasks: 4,
      maxMemoryUsage: 1024 * 1024 * 1024,
      maxExecutionTime: 900000,
      reliability: 0.9,
      speed: 0.75,
      quality: 0.9,
    },
    defaultConfig: {
      autonomyLevel: 0.7,
      learningEnabled: true,
      maxTasksPerHour: 15,
    },
    category: 'data',
  },

  architect: {
    type: 'architect',
    name: 'System Architect',
    description: 'Designs system architecture and solutions',
    capabilities: {
      codeGeneration: false,
      codeReview: true,
      testing: false,
      documentation: true,
      research: true,
      analysis: true,
      webSearch: false,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: false,
      languages: ['typescript', 'javascript', 'python'],
      frameworks: [],
      domains: ['software-architecture', 'system-design', 'data-modeling'],
      tools: ['diagram-generator', 'code-analyzer', 'api-designer'],
      maxConcurrentTasks: 2,
      maxMemoryUsage: 512 * 1024 * 1024,
      maxExecutionTime: 900000,
      reliability: 0.95,
      speed: 0.7,
      quality: 0.95,
    },
    defaultConfig: {
      autonomyLevel: 0.8,
      learningEnabled: true,
      maxTasksPerHour: 5,
    },
    category: 'architecture',
  },

  tester: {
    type: 'tester',
    name: 'QA Engineer',
    description: 'Tests and validates functionality',
    capabilities: {
      codeGeneration: false,
      codeReview: true,
      testing: true,
      documentation: true,
      research: false,
      analysis: true,
      webSearch: false,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: true,
      languages: ['typescript', 'javascript', 'python'],
      frameworks: ['jest', 'vitest', 'cypress', 'playwright'],
      domains: ['testing', 'quality-assurance', 'test-automation'],
      tools: ['test-runner', 'coverage-analyzer', 'test-generator'],
      maxConcurrentTasks: 3,
      maxMemoryUsage: 256 * 1024 * 1024,
      maxExecutionTime: 600000,
      reliability: 0.9,
      speed: 0.8,
      quality: 0.9,
    },
    defaultConfig: {
      autonomyLevel: 0.7,
      learningEnabled: true,
      maxTasksPerHour: 15,
    },
    category: 'testing',
  },

  reviewer: {
    type: 'reviewer',
    name: 'Code Reviewer',
    description: 'Reviews and validates work quality',
    capabilities: {
      codeGeneration: false,
      codeReview: true,
      testing: false,
      documentation: true,
      research: false,
      analysis: true,
      webSearch: false,
      apiIntegration: false,
      fileSystem: true,
      terminalAccess: false,
      languages: ['typescript', 'javascript', 'python', 'rust'],
      frameworks: [],
      domains: ['code-review', 'quality-assurance', 'best-practices'],
      tools: ['static-analyzer', 'code-quality-checker', 'security-scanner'],
      maxConcurrentTasks: 2,
      maxMemoryUsage: 256 * 1024 * 1024,
      maxExecutionTime: 450000,
      reliability: 0.95,
      speed: 0.8,
      quality: 0.95,
    },
    defaultConfig: {
      autonomyLevel: 0.8,
      learningEnabled: true,
      maxTasksPerHour: 12,
    },
    category: 'testing',
  },

  optimizer: {
    type: 'optimizer',
    name: 'Performance Optimizer',
    description: 'Optimizes performance and efficiency',
    capabilities: {
      codeGeneration: true,
      codeReview: true,
      testing: true,
      documentation: true,
      research: false,
      analysis: true,
      webSearch: false,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: true,
      languages: ['typescript', 'javascript', 'python', 'rust'],
      frameworks: [],
      domains: ['performance-optimization', 'resource-optimization', 'scalability'],
      tools: ['profiler', 'benchmark', 'analyzer'],
      maxConcurrentTasks: 2,
      maxMemoryUsage: 512 * 1024 * 1024,
      maxExecutionTime: 900000,
      reliability: 0.9,
      speed: 0.7,
      quality: 0.9,
    },
    defaultConfig: {
      autonomyLevel: 0.7,
      learningEnabled: true,
      maxTasksPerHour: 8,
    },
    category: 'specialized',
  },

  documenter: {
    type: 'documenter',
    name: 'Documentation Specialist',
    description: 'Creates and maintains documentation',
    capabilities: {
      codeGeneration: false,
      codeReview: false,
      testing: false,
      documentation: true,
      research: true,
      analysis: true,
      webSearch: false,
      apiIntegration: false,
      fileSystem: true,
      terminalAccess: false,
      languages: [],
      frameworks: [],
      domains: ['documentation', 'technical-writing', 'knowledge-management'],
      tools: ['document-writer', 'diagram-generator'],
      maxConcurrentTasks: 3,
      maxMemoryUsage: 256 * 1024 * 1024,
      maxExecutionTime: 600000,
      reliability: 0.95,
      speed: 0.8,
      quality: 0.95,
    },
    defaultConfig: {
      autonomyLevel: 0.7,
      learningEnabled: true,
      maxTasksPerHour: 10,
    },
    category: 'business',
  },

  monitor: {
    type: 'monitor',
    name: 'System Monitor',
    description: 'Monitors system health and performance',
    capabilities: {
      codeGeneration: false,
      codeReview: false,
      testing: false,
      documentation: true,
      research: false,
      analysis: true,
      webSearch: false,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: false,
      languages: [],
      frameworks: [],
      domains: ['monitoring', 'alerting', 'diagnostics'],
      tools: ['monitoring-dashboard', 'alerting-system', 'log-analyzer'],
      maxConcurrentTasks: 5,
      maxMemoryUsage: 256 * 1024 * 1024,
      maxExecutionTime: 86400000,
      reliability: 0.99,
      speed: 0.9,
      quality: 0.9,
    },
    defaultConfig: {
      autonomyLevel: 0.9,
      learningEnabled: true,
      maxTasksPerHour: 100,
    },
    category: 'devops',
  },

  specialist: {
    type: 'specialist',
    name: 'Domain Specialist',
    description: 'Domain-specific specialized agent',
    capabilities: {
      codeGeneration: true,
      codeReview: true,
      testing: true,
      documentation: true,
      research: true,
      analysis: true,
      webSearch: true,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: true,
      languages: ['typescript', 'javascript', 'python'],
      frameworks: [],
      domains: ['custom-domain'],
      tools: [],
      maxConcurrentTasks: 2,
      maxMemoryUsage: 512 * 1024 * 1024,
      maxExecutionTime: 900000,
      reliability: 0.9,
      speed: 0.75,
      quality: 0.9,
    },
    defaultConfig: {
      autonomyLevel: 0.7,
      learningEnabled: true,
      maxTasksPerHour: 10,
    },
    category: 'specialized',
  },

  // Additional specialized agent types can be added here
  // For now, providing essential agent types with placeholders for others
  'design-architect': {
    type: 'design-architect',
    name: 'Design Architect',
    description: 'UI/UX and component design specialist',
    capabilities: {
      codeGeneration: false,
      codeReview: true,
      testing: false,
      documentation: true,
      research: true,
      analysis: true,
      webSearch: false,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: false,
      languages: ['typescript', 'javascript'],
      frameworks: ['react', 'vue', 'svelte'],
      domains: ['ui-design', 'ux-design', 'component-architecture'],
      tools: ['figma', 'sketch', 'storybook'],
      maxConcurrentTasks: 2,
      maxMemoryUsage: 512 * 1024 * 1024,
      maxExecutionTime: 900000,
      reliability: 0.9,
      speed: 0.7,
      quality: 0.95,
    },
    defaultConfig: {
      autonomyLevel: 0.7,
      learningEnabled: true,
      maxTasksPerHour: 8,
    },
    category: 'architecture',
  },

  'system-architect': {
    type: 'system-architect',
    name: 'System Architect',
    description: 'System-level architecture design specialist',
    capabilities: {
      codeGeneration: false,
      codeReview: true,
      testing: false,
      documentation: true,
      research: true,
      analysis: true,
      webSearch: false,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: false,
      languages: ['typescript', 'javascript', 'python'],
      frameworks: [],
      domains: ['system-architecture', 'scalability', 'distributed-systems'],
      tools: ['architecture-analyzer', 'system-modeler'],
      maxConcurrentTasks: 1,
      maxMemoryUsage: 512 * 1024 * 1024,
      maxExecutionTime: 900000,
      reliability: 0.95,
      speed: 0.7,
      quality: 0.95,
    },
    defaultConfig: {
      autonomyLevel: 0.8,
      learningEnabled: true,
      maxTasksPerHour: 5,
    },
    category: 'architecture',
  },

  'task-planner': {
    type: 'task-planner',
    name: 'Task Planner',
    description: 'Project management and task breakdown specialist',
    capabilities: {
      codeGeneration: false,
      codeReview: false,
      testing: false,
      documentation: true,
      research: false,
      analysis: true,
      webSearch: false,
      apiIntegration: false,
      fileSystem: true,
      terminalAccess: false,
      languages: [],
      frameworks: [],
      domains: ['project-management', 'task-breakdown', 'agile-planning'],
      tools: ['task-scheduler', 'dependency-analyzer'],
      maxConcurrentTasks: 3,
      maxMemoryUsage: 256 * 1024 * 1024,
      maxExecutionTime: 300000,
      reliability: 0.95,
      speed: 0.85,
      quality: 0.9,
    },
    defaultConfig: {
      autonomyLevel: 0.8,
      learningEnabled: true,
      maxTasksPerHour: 20,
    },
    category: 'business',
  },

  developer: {
    type: 'developer',
    name: 'Full-Stack Developer',
    description: 'Full-stack development and implementation',
    capabilities: {
      codeGeneration: true,
      codeReview: true,
      testing: true,
      documentation: true,
      research: false,
      analysis: true,
      webSearch: false,
      apiIntegration: true,
      fileSystem: true,
      terminalAccess: true,
      languages: ['typescript', 'javascript', 'python', 'rust'],
      frameworks: ['react', 'node', 'express', 'fastapi'],
      domains: ['web-development', 'backend', 'frontend'],
      tools: ['git', 'editor', 'debugger', 'linter'],
      maxConcurrentTasks: 3,
      maxMemoryUsage: 512 * 1024 * 1024,
      maxExecutionTime: 1200000,
      reliability: 0.95,
      speed: 0.7,
      quality: 0.95,
    },
    defaultConfig: {
      autonomyLevel: 0.6,
      learningEnabled: true,
      maxTasksPerHour: 10,
    },
    category: 'development',
  },

  'requirements-engineer': {
    type: 'requirements-engineer',
    name: 'Requirements Engineer',
    description: 'Requirements analysis and documentation specialist',
    capabilities: {
      codeGeneration: false,
      codeReview: false,
      testing: false,
      documentation: true,
      research: true,
      analysis: true,
      webSearch: true,
      apiIntegration: false,
      fileSystem: true,
      terminalAccess: false,
      languages: [],
      frameworks: [],
      domains: ['requirements-engineering', 'user-stories', 'specifications'],
      tools: ['document-writer', 'nlp-processor'],
      maxConcurrentTasks: 2,
      maxMemoryUsage: 256 * 1024 * 1024,
      maxExecutionTime: 300000,
      reliability: 0.95,
      speed: 0.8,
      quality: 0.95,
    },
    defaultConfig: {
      autonomyLevel: 0.8,
      learningEnabled: true,
      maxTasksPerHour: 10,
    },
    category: 'business',
  },

  'steering-author': {
    type: 'steering-author',
    name: 'Steering Author',
    description: 'Governance and steering documentation specialist',
    capabilities: {
      codeGeneration: false,
      codeReview: true,
      testing: false,
      documentation: true,
      research: true,
      analysis: true,
      webSearch: false,
      apiIntegration: false,
      fileSystem: true,
      terminalAccess: false,
      languages: [],
      frameworks: [],
      domains: ['documentation', 'governance', 'knowledge-management'],
      tools: ['document-writer', 'content-analyzer'],
      maxConcurrentTasks: 1,
      maxMemoryUsage: 256 * 1024 * 1024,
      maxExecutionTime: 300000,
      reliability: 0.95,
      speed: 0.7,
      quality: 0.98,
    },
    defaultConfig: {
      autonomyLevel: 0.7,
      learningEnabled: true,
      maxTasksPerHour: 5,
    },
    category: 'business',
  },

  // Placeholder implementations for remaining agent types
  // These can be expanded with full capabilities as needed
  'backend-dev': {} as AgentTypeDefinition,
  'api-designer': {} as AgentTypeDefinition,
  'database-architect': {} as AgentTypeDefinition,
  'microservices-engineer': {} as AgentTypeDefinition,
  'frontend-dev': {} as AgentTypeDefinition,
  'ui-designer': {} as AgentTypeDefinition,
  'mobile-dev': {} as AgentTypeDefinition,
  'cicd-engineer': {} as AgentTypeDefinition,
  'cloud-architect': {} as AgentTypeDefinition,
  'security-engineer': {} as AgentTypeDefinition,
  'performance-engineer': {} as AgentTypeDefinition,
  'data-scientist': {} as AgentTypeDefinition,
  'ml-engineer': {} as AgentTypeDefinition,
  'data-engineer': {} as AgentTypeDefinition,
  'analytics-engineer': {} as AgentTypeDefinition,
  'qa-engineer': {} as AgentTypeDefinition,
  'test-automation-engineer': {} as AgentTypeDefinition,
  'security-tester': {} as AgentTypeDefinition,
  'project-manager': {} as AgentTypeDefinition,
  'product-owner': {} as AgentTypeDefinition,
  'scrum-master': {} as AgentTypeDefinition,
  'business-analyst': {} as AgentTypeDefinition,
  'technical-writer': {} as AgentTypeDefinition,
  'seo-specialist': {} as AgentTypeDefinition,
  'marketing-specialist': {} as AgentTypeDefinition,
};

/**
 * Get agent type definition
 */
export function getAgentTypeDefinition(type: AgentType): AgentTypeDefinition | undefined {
  return AGENT_TYPES[type];
}

/**
 * Get all agent types by category
 */
export function getAgentTypesByCategory(
  category: AgentTypeDefinition['category']
): AgentTypeDefinition[] {
  return Object.values(AGENT_TYPES).filter((def) => def.category === category);
}

/**
 * Get agent types that match required capabilities
 */
export function findAgentTypesForCapabilities(requiredCapabilities: string[]): AgentType[] {
  return Object.entries(AGENT_TYPES)
    .filter(([_, def]) => {
      if (!def.capabilities) return false;
      const agentCaps = [
        ...def.capabilities.languages,
        ...def.capabilities.frameworks,
        ...def.capabilities.domains,
        ...def.capabilities.tools,
      ];
      return requiredCapabilities.every((required) =>
        agentCaps.some((cap) => cap.toLowerCase().includes(required.toLowerCase()))
      );
    })
    .map(([type]) => type as AgentType);
}
